services:
  - type: web
    name: my-web-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    pythonVersion: "3.8"  # Ensure the Python version is specified
